variables:
  GIT_SUBMODULE_STRATEGY: recursive
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  RELEASE_TAG: $CI_REGISTRY_IMAGE:latest

stages:
  - build
  - test
  - release

default:
  image: docker/compose
  before_script:
    - docker info

build-image:
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG

test-image:
  stage: test
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $IMAGE_TAG
    - docker run -d --name bitnp-accounts -e acct_client_id="bitnp-accounts" -e acct_client_secret="client_secret" -e acct_session_secret="session_secret" -e acct_invitation_secret="invitation_secret" $IMAGE_TAG
    - sleep 10
    - 'if docker ps -a | grep bitnp-accounts | grep "Stop\|Restart"; then docker logs bitnp-accounts;exit 1; fi'
    - 'if ! wget "http://`docker inspect -f ''{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}'' bitnp-accounts`/" -O - -q | grep "网协通行证"; then docker logs bitnp-accounts;exit 1; fi'
    - docker ps
  after_script:
    - docker rm -f bitnp-accounts

test-docker-compose-config:
  stage: test
  script:
    - touch .env
    - docker-compose config

release-image:
  stage: release
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - docker pull $IMAGE_TAG
    - docker tag $IMAGE_TAG $RELEASE_TAG
    - docker push $RELEASE_TAG
  only:
    - master
