version: "2.1"
services:
  accountsvc:
    image: docker.bitnp.net/bitnp/keycloak-account-service:master
    env_file: .env
    environment: # more config in .env which starts with acct_
      VIRTUAL_HOST: accounts.bitnp.net, accounts.proxy.bitnp.net
      VIRTUAL_PORT: 80
      FORWARDED_ALLOW_IPS: 172.17.0.3 # change to proxy IP accordingly
      TZ: Asia/Shanghai
    network_mode: bridge
    external_links:
      - mysql
      - ldap
    expose:
      - 80
